### ISSUE TITLE
Optimize Geometry - "Error interpreting obabel MDL output"

### ISSUE THREAD

**Issue by TristanBomb** [cryos/avogadro#35]
OS: Windows 8.1 64-bit
Avogadro 2 v0.80

When I attempt to use Open Babel's "Optimize Geometry" feature, I get an "error interpreting obabel MDL output." This appears to occur on any molecule - I have attempted methane, hydrogen peroxide, water, and nitromethane - and with any configuration of Optimize Geometry.

I installed Avogadro v1.1.1 and it works in that old version. I also noticed that "Adjust Hydrogens" is no longer functional in Avogadro 2, but I suppose that's a less pressing issue.

**Comment by cryos** [comment]
Thanks, I will look into it. I am getting ready to generate new binaries for an updated release. I will double check this works once I have them built.

**Comment by ghutchis** [comment]
I think this should be closed and moved to the Avogadro2 project issues.

**Comment by cryos** [comment]
Agreed, you can report at https://github.com/OpenChemistry/avogadroapp, can't move issues unfortunately, so closing and will look at this.
