### ISSUE TITLE
Problem with displaying molecules in 0.9.7

### ISSUE THREAD

**Issue by cryos** [cryos/avogadro#442]
Hi, Marcus!
I installed Avogadro (from source code) on two computers with Mandriva
2009.1. And I have a problem on one of them.
When I open a file or draw something, the structure is not displayed.
Here is screenshot: http://picamigo.com/out.php/i11090_avogadro1.png
And one more, where background color is set to white:
http://picamigo.com/out.php/i11091_avogadro2.png
Only axes and cycles are displayed properly. I tried to change quality
settings, disabled KDE effects, but it did not help. The video driver works
fine with almost all OpenGL applications.

Reported by: bizdelnick

**Comment by ghutchis** [comment]
This is ancient. There may still be old Linux driver issues, but I'd rather revisit if they exist with a modern stack and modern Avogadro version.
