### ISSUE TITLE
Accessing other molecules in multimol SDF file fails

### ISSUE THREAD

**Issue by cryos** [cryos/avogadro#475]
Following Geoff's comment on my blog, I tried out multimol SDF file support in Avo 1.0 on Win. One file worked and I could access the other molecules through View/All Molecules In File.

Another file didn't. Please find attached an SDF with two molecules. Each can be opened by Avogadro individually, but the second molecule of the multimol cannot be accessed.

Reported by: @baoilleach

**Comment by ghutchis** [comment]
The problem is that if you have multiple molecules in a SD file, but it's the same compound, Open Babel will represent this as conformers. It's not a bug.
