### ISSUE TITLE
highlight ring feature not working for polyhedrons

### ISSUE THREAD

**Issue by cryos** [cryos/avogadro#485]
- draw for example a cube in Avogadro 1.0
- use the highlight ring feature

Result: one ring is not highlighted

This might be intended because it is nice to be able to look into a bucky ball but is annoying when having several polyhedrons in a drawing. The attached file contains 3 polyhedrons. As result 3 rings of the dodecahedron are not highlighted.

Reported by: donovaly

**Comment by ghutchis** [comment]
While the ring engine is cool, I think it's very tricky to ensure the winding is always correct for OpenGL. I'm closing this.
