### ISSUE TITLE
Interface of Avogadro can't be changed to Russian.

### ISSUE THREAD

**Issue by cryos** [cryos/avogadro#501]
avogadro
"Avogadro version:      1.0.0   Git:
LibAvogadro version:    1.0.0   Git:    "
Locale:  "C"
Libavogadro translations not found.
"System has OpenGL support."
"About to test OpenGL capabilities."
"OpenGL capabilities found: "
         "Double Buffering."
         "Direct Rendering."
         "Antialiasing."
Loading plugins: "/usr/bin/../lib64/avogadro/1_0"
Searching for plugins in "/usr/bin/../lib64/avogadro/1_0/colors"
Searching for plugins in "/usr/bin/../lib64/avogadro/1_0/engines"
Searching for plugins in "/usr/bin/../lib64/avogadro/1_0/extensions"
Searching for plugins in "/usr/bin/../lib64/avogadro/1_0/tools"
Searching for plugins in "/usr/bin/../lib64/avogadro/1_0/contrib"
Loading plugins: "/home/victor/.avogadro/1_0/plugins"
Searching for plugins in "/home/victor/.avogadro/1_0/plugins/colors"
Searching for plugins in "/home/victor/.avogadro/1_0/plugins/engines"
Searching for plugins in "/home/victor/.avogadro/1_0/plugins/extensions"
Searching for plugins in "/home/victor/.avogadro/1_0/plugins/tools"
Searching for plugins in "/home/victor/.avogadro/1_0/plugins/contrib"
QStackedLayout::setCurrentWidget: Widget 0x12b4c40 not contained in stack
GLWidget initialisation...
GLSL support enabled, OpenGL 2.0 support confirmed.
GLWidget initialised...
createObjects()
libpng warning: Ignoring attempt to set cHRM RGB triangle with zero area

And Avogadro starts with English Interface...

But If it starts with command: "LC_ALL="ru_RU.UTF-8" avogadro" then interface changes to Russian.

Reported by: *anonymous

**Comment by ghutchis** [comment]
Marking closed - seems like an old Qt - Gentoo issue, not an Avogadro one.
