### ISSUE TITLE
Saving as PDB file gives incorrect CONECT records

### ISSUE THREAD

**Issue by cryos** [cryos/avogadro#510]
In the Mac 1.0.0 version, saving structures in PDB format always ( as far as I can tell) produces some  incorrect CONECT records where atoms numbers are repeated in the same CONECT record.

Please see the attached pdf file where I have pointed out some of these occurrences.

Regards, and keep up the good work!

Dean
Dr. Den Cuebas
Dept. of Chemistry
Missouri State University
Springfield, MO 65804

Reported by: *anonymous

**Comment by ghutchis** [comment]
This was fixed in Open Babel ages ago. (Although people *still* ask for the non-standard CONECT records.)
