### ISSUE TITLE
12-coordinate bonds not displayed

### ISSUE THREAD

**Issue by cryos** [cryos/avogadro#543]
There seems to be a limit on the number of bonds a particular atom may have.  I am working with transition metals which may be bonded to 12 other atoms.  These bonds should be displayed.  I am attaching a set of xyz coordinates for a Pt13 cluster which demonstrate this problem along with images produced (incorrectly) with Avogadro and (correctly) with Jmol.

I am using Avogadro 1.0.1 on Mac OS X 10.6.4.

Reported by: *anonymous

**Comment by ghutchis** [comment]
Marking closed. While it's possible to manually add 12 bonds, the code should not automatically do this.
