### ISSUE TITLE
Segfault when opening files with an xml file ending

### ISSUE THREAD

**Issue by cryos** [cryos/avogadro#576]
Peter reported this to me, and I have been able to reproduce it on Windows and Linux. If you have a CML file, but it has a .xml file ending it causes a segfault. I looked at this in GDB on Linux and it looks like it is the code in Open Babel attempting to determine a default XML reader (it hits some null pointers). This should possibly be reported to Open Babel separately assuming we are using the OB API correctly.

Reported by: @cryos

**Comment by ghutchis** [comment]
Works for me.
