### ISSUE TITLE
Fail to un to Windows Vista

### ISSUE THREAD

**Issue by cryos** [cryos/avogadro#629]
I installed Avogadro 1.0.3 version on my WIndows Vista system. But whenever I click the avogadro icon, a window pump up and say that "avogadro.exe has stopped working" Re-installing the program does not solve the problem. Neither does trying the old version of avogadro.

I also use avogadro on Linux and Windows XP system, and it works perfectly well.  Could someone tell me what is wrong with running Avogadro on Windows vista system (64bit)?

Thank you!

Reported by: *anonymous

**Comment by ghutchis** [comment]
Works for me, and we're well past 1.0.3.
