### ISSUE TITLE
Problems with Dipole Moment Calculation

### ISSUE THREAD

**Issue by cryos** [cryos/avogadro#706]
Hello, 
The algorithm for calculation of the molecular dipole does not seem to work for carbon dioxide. After construction of the molecule, a very large dipole (several Debye) is reported, even though the molecule is symmetric about the central carbon atom. This large dipole exists after geometry optimization, even though the reported bond angle in Avogadro is 180 degrees and both bond lengths are the same. The same problem also occurs in version 1.1.0. Insight into this problem would be helpful.
Thanks,
Steve

Reported by: *anonymous

**Comment by ghutchis** [comment]
Works for me. I'm closing this - if it comes up with 1.2, I'm happy to revisit.
