### ISSUE TITLE
Crash producing density surface from fchk (Mac)

### ISSUE THREAD

**Issue by cryos** [cryos/avogadro#709]
I'm trying to use Avogadro to produce an isodensity surface coloured with the electrostatic potential, using a Gaussian 09 fchk file. The process works fine for a small test molecule (ammonia), but I get a crash when working with the molecule of interest (38 atoms). I would upload the fchk file in question, but it's 47 MB (perhaps part of the problem) - we could work out a way to transfer it if necessary. OS is Mac OS 10.8.2. 

The crash generates the following (snipped) info:

Process:         Avogadro [48462]
Path:            /Applications/Avogadro.app/Contents/MacOS/Avogadro
Identifier:      net.sourceforge
Version:         ??? (1.1.0)
Code Type:       X86-64 (Native)
Parent Process:  launchd [144]
User ID:         7792

Date/Time:       2013-01-21 09:11:57.304 +0000
OS Version:      Mac OS X 10.8.2 (12C2037)
Report Version:  10

Interval Since Last Report:          175557 sec
Crashes Since Last Report:           2
Per-App Interval Since Last Report:  29704 sec
Per-App Crashes Since Last Report:   2
Anonymous UUID:                      75223243-5BEA-931F-F2FD-3DB79C34B40A

Crashed Thread:  8

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000

Application Specific Information:
*** error for object 0x104aaa000: incorrect checksum for freed object - object was probably modified after being freed.
 

Reported by: *anonymous

**Comment by ghutchis** [comment]
Works for me - I use fchk files much larger than 38 atoms. Perhaps this was an issue with 'f' or higher momentum orbitals? These bugs are fixed too.
