### ISSUE TITLE
Dipole Moments always underestimated

### ISSUE THREAD

**Issue by cryos** [cryos/avogadro#763]
Dear Avogadro Developers,
I am using Ubuntu 14.04 as the operating system and Avogadro version 1.1.1. It seems that the magnitude of the dipole moment for polar molecules constructed in Avogadro are underestimated. For example, water has an experimentally determined dipole moment of 1.85 D, whereas the dipole moment calculated using Avogadro is 0.245 D.Ammonia has an experimental dipole moment of 1.47D but is calculated to be 0.135 D. Finally methyl chloride has an experimental dipole moment of 1.87 D, but the predicted dipole moment is 0.270 D. So it seems that the dipole moments are too small by a  factor of approximately 6 - 8. Any idea the source of the bias in dipole moments?

Reported by: *anonymous

**Comment by ghutchis** [comment]
This bug was fixed. Granted, we can't exactly match the experimental dipole moments, but a bug with conversion to debye was fixed.
