### ISSUE TITLE
Cannot compile on Ubuntu 14.04, problem with <Eigen/Core>

### ISSUE THREAD

**Issue by cryos** [cryos/avogadro#766]
Dear Developers, 

I'm trying to install the latest version, as described here (http://xtalopt.openmolecules.net/wiki/index.fcgi/wiki/Installation), and I think I have done everthing by the books. If anyone could help it would be tremedeously appreciated. 

The cmake command mostly fairs well (see below), but has a few messages to the developers. When I then try to run make, it crashes complaining about "fatal error: Eigen/Core: No such file or directory
 #include <Eigen/Core>"

I'm running a Ubuntu 14.04 on an intel i5, all freshly installed. I am not familiar with what it is exactly, but I have installed both eigen2 and eigen3, and all other necessary dependancies (as far as I can tell), all using ubuntu's package manager. It's crucial I get it to work... argh.  

Very thankful for help, 
Martin 

martin@box:~/Programs/avogadro/build$ cmake .. -DOPENBABEL2_INCLUDE_DIR=$HOME/include/openbabel-2.0 -DOPENBABEL2_LIBRARIES=$HOME/lib/libopenbabel.so   -DOPENBABEL2_VERSION_MET=true -DOPENBABEL_IS_NEWER_THAN_2_2_99=true -DCMAKE_INSTALL_PREFIX=$HOME
-- The C compiler identification is GNU 4.8.2
-- The CXX compiler identification is GNU 4.8.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- The build type is RelWithDebInfo
-- Performing Test HAVE_NO_RTTI
-- Performing Test HAVE_NO_RTTI - Success
-- Performing Test HAVE_RTTI
-- Performing Test HAVE_RTTI - Success
-- Performing Test HAVE_GCC_VISIBILITY
-- Performing Test HAVE_GCC_VISIBILITY - Success
-- Performing Test COMPILES_WITHOUT_FPERMISSIVE
-- Performing Test COMPILES_WITHOUT_FPERMISSIVE - Failed
-- Looking for Q_WS_X11
-- Looking for Q_WS_X11 - found
-- Looking for Q_WS_WIN
-- Looking for Q_WS_WIN - not found
-- Looking for Q_WS_QWS
-- Looking for Q_WS_QWS - not found
-- Looking for Q_WS_MAC
-- Looking for Q_WS_MAC - not found
-- Found Qt4: /usr/bin/qmake (found suitable version "4.8.6", minimum required is "4.6.0") 
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib/x86_64-linux-gnu/libX11.so
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libGL.so  
-- Found lupdate: /usr/bin/lupdate-qt4
-- Found lrelease: /usr/bin/lrelease-qt4
-- Found lconvert: /usr/bin/lconvert
-- Found Eigen3: /usr/include/eigen3 (Required is at least version "2.91.0") 
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
-- Found OpenBabel2 executable: /home/martin/bin/babel
-- Git revision found to be 3561ccf
-- Found Git revision is: 3561ccf
-- Building development version from Git clone.
-- Searching for python dependencies...
-- [1/5] Boost Python
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   python
-- Boost Python found...
-- [2/5] Python Libraries
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so  
-- [3/5] Python Interpreter
-- Found PythonInterp: /usr/bin/python (found version "2.7.6") 
-- [4/5] Numpy Module
-- Numpy headers found
-- [5/5] SIP Module
-- SIP version 265989 found
-- Found SIP: /usr/include/python2.7  
-- All python dependencies found - Python support enabled
-- Threaded OpenGL rendering not enabled
-- RPath support enabled for installed binaries and libraries
-- Setting new boost python libraries
-- Enabled python terminal
-- Found Qt4: /usr/bin/qmake (found suitable version "4.8.6", minimum required is "4.6") 
-- Found Eigen2: /usr/include/eigen2 (Required is at least version "2.0.0") 
-- Linking in static plugins: bsdyengine;navigatetool;elementcolor
-- Python site-packages directory: /usr/lib/python2.7/dist-packages
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.6") 
-- docbook tools not found, doc targets disabled
-- Configuring done
CMake Warning (dev) in libavogadro/src/CMakeLists.txt:
  Policy CMP0022 is not set: INTERFACE_LINK_LIBRARIES defines the link
  interface.  Run "cmake --help-policy CMP0022" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  Target "avogadro" has an INTERFACE_LINK_LIBRARIES property which differs
  from its LINK_INTERFACE_LIBRARIES properties.

  INTERFACE_LINK_LIBRARIES:

```
/home/martin/lib/libopenbabel.so;/usr/lib/x86_64-linux-gnu/libQtOpenGL.so;/usr/lib/x86_64-linux-gnu/libQtGui.so;/usr/lib/x86_64-linux-gnu/libQtCore.so;/usr/lib/x86_64-linux-gnu/libGLU.so;/usr/lib/x86_64-linux-gnu/libGL.so;/usr/lib/x86_64-linux-gnu/libSM.so;/usr/lib/x86_64-linux-gnu/libICE.so;/usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so;/usr/lib/x86_64-linux-gnu/libpython2.7.so;/usr/lib/x86_64-linux-gnu/libboost_python.so;bsdyengine;navigatetool;elementcolor
```

  LINK_INTERFACE_LIBRARIES:

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in libavogadro/src/extensions/surfaces/openqube/CMakeLists.txt:
  Policy CMP0022 is not set: INTERFACE_LINK_LIBRARIES defines the link
  interface.  Run "cmake --help-policy CMP0022" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  Target "OpenQube" has an INTERFACE_LINK_LIBRARIES property which differs
  from its LINK_INTERFACE_LIBRARIES properties.

  INTERFACE_LINK_LIBRARIES:

```
$<$<NOT:$<CONFIG:DEBUG>>:/usr/lib/x86_64-linux-gnu/libQtCore.so>;$<$<CONFIG:DEBUG>:/usr/lib/x86_64-linux-gnu/libQtCore.so>
```

  LINK_INTERFACE_LIBRARIES:

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

```
OPENBABEL_IS_NEWER_THAN_2_2_99
```

-- Build files have been written to: /home/martin/Programs/avogadro/build

martin@box:~/Programs/avogadro/build$ make -j3 
[  0%] [  0%] [  0%] Generating ui_bsdysettingswidget.h
Generating moc_elementcolor.cxx
Generating qrc_navigatetool.cxx
[  1%] [  1%] Generating moc_bsdyengine.cxx
Generating moc_navigatetool.cxx
Scanning dependencies of target elementcolor
[  1%] Generating ui_navigatesettingswidget.h
[  1%] Scanning dependencies of target bsdyengine
Scanning dependencies of target navigatetool
Building CXX object libavogadro/src/colors/CMakeFiles/elementcolor.dir/elementcolor.cpp.o
[  1%] [  1%] Building CXX object libavogadro/src/tools/CMakeFiles/navigatetool.dir/navigatetool.cpp.o
Building CXX object libavogadro/src/engines/CMakeFiles/bsdyengine.dir/bsdyengine.cpp.o
In file included from /home/martin/Programs/avogadro/libavogadro/src/colors/elementcolor.cpp:27:0:
/home/martin/Programs/avogadro/build/libavogadro/include/avogadro/primitive.h:34:22: fatal error: Eigen/Core: No such file or directory
 #include <Eigen/Core>
                      ^
compilation terminated.
In file included from /home/martin/Programs/avogadro/libavogadro/src/tools/navigatetool.h:29:0,
                 from /home/martin/Programs/avogadro/libavogadro/src/tools/navigatetool.cpp:26:
/home/martin/Programs/avogadro/build/libavogadro/include/avogadro/glwidget.h:32:22: fatal error: Eigen/Core: No such file or directory
 #include <Eigen/Core>
                      ^
compilation terminated.
In file included from /home/martin/Programs/avogadro/build/libavogadro/include/avogadro/primitivelist.h:29:0,
                 from /home/martin/Programs/avogadro/build/libavogadro/include/avogadro/engine.h:37,
                 from /home/martin/Programs/avogadro/libavogadro/src/engines/bsdyengine.h:29,
                 from /home/martin/Programs/avogadro/libavogadro/src/engines/bsdyengine.cpp:25:
/home/martin/Programs/avogadro/build/libavogadro/include/avogadro/primitive.h:34:22: fatal error: Eigen/Core: No such file or directory
 #include <Eigen/Core>
                      ^
compilation terminated.
make[2]: **\* [libavogadro/src/colors/CMakeFiles/elementcolor.dir/elementcolor.cpp.o] Error 1
make[1]: **\* [libavogadro/src/colors/CMakeFiles/elementcolor.dir/all] Error 2
make[1]: **\* Waiting for unfinished jobs....
[  1%] Building CXX object libavogadro/src/engines/CMakeFiles/bsdyengine.dir/moc_bsdyengine.cxx.o
make[2]: **\* [libavogadro/src/tools/CMakeFiles/navigatetool.dir/navigatetool.cpp.o] Error 1
make[1]: **\* [libavogadro/src/tools/CMakeFiles/navigatetool.dir/all] Error 2
In file included from /home/martin/Programs/avogadro/build/libavogadro/include/avogadro/primitivelist.h:29:0,
                 from /home/martin/Programs/avogadro/build/libavogadro/include/avogadro/engine.h:37,
                 from /home/martin/Programs/avogadro/build/libavogadro/src/engines/../../../../libavogadro/src/engines/bsdyengine.h:29,
                 from /home/martin/Programs/avogadro/build/libavogadro/src/engines/moc_bsdyengine.cxx:9:
/home/martin/Programs/avogadro/build/libavogadro/include/avogadro/primitive.h:34:22: fatal error: Eigen/Core: No such file or directory
 #include <Eigen/Core>
                      ^
compilation terminated.
make[2]: **\* [libavogadro/src/engines/CMakeFiles/bsdyengine.dir/bsdyengine.cpp.o] Error 1
make[2]: **\* Waiting for unfinished jobs....
make[2]: **\* [libavogadro/src/engines/CMakeFiles/bsdyengine.dir/moc_bsdyengine.cxx.o] Error 1
make[1]: **\* [libavogadro/src/engines/CMakeFiles/bsdyengine.dir/all] Error 2
make: **\* [all] Error 2

Reported by: *anonymous

**Comment by probonopd** [comment]
I am running into a similar issue on Ubuntu 14.04 with `libeigen2-dev` installed:

```
CMake Error at /usr/local/cmake-3.9.2/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Eigen3 (missing: EIGEN3_INCLUDE_DIR EIGEN3_VERSION_OK)
  (Required is at least version "2.91.0")
Call Stack (most recent call first):
  /usr/local/cmake-3.9.2/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindEigen3.cmake:76 (find_package_handle_standard_args)
  CMakeLists.txt:234 (find_package)
```

**Comment by ghutchis** [comment]
As noted above, this bug is closed. `master` for Avo1 uses Eigen3. If you don't have it installed, you won't be able to build - you note `libeigen2-dev` not Eigen3

**Comment by probonopd** [comment]
Thanks, indeed installing `libeigen2-dev` solved this for me.
