### ISSUE TITLE
Measurement text is garbled

### ISSUE THREAD

**Issue by KELedbetter** [cryos/avogadro#841]
Using the click to measure tool in version 1.2.0 on Windows 10, the text of measurements appears garbled. Screen resolution is 3200x1800. 
![avogadromeasure](https://cloud.githubusercontent.com/assets/22223827/18562428/7d47dcb8-7b38-11e6-9a94-4e09e16fb908.PNG)

**Comment by ghutchis** [comment]
Out of curiosity, can you try Avogadro 2 (http://www.openchemistry.org/downloads/) and see if the text is better?

I suspect the "solution" is to push to finish 2.0, since the rendering in 1.2.0 is decidedly hacky.

**Comment by KELedbetter** [comment]
That worked perfectly. Thank you!
