### ISSUE TITLE
how to install the Z-matrix module in Avogadro

### ISSUE THREAD

**Issue by dlopezduran** [cryos/avogadro#853]
Hi all,
 I have already installed Avogadro in my computer. In this setup the Z-matrix editor is not include and I need to install now that module. I am looking at the web how to do it; but I find anything. I would appreciate any help.
 These are the data of my setup:
Operating system: Mac OS X El Capitan version 10.11.4
Avogadro version: 1.1.1 (bot Application and Library version)
Avogadro QT version: 4.8.5
(Open Babel version unknown)
 Thank you very much.

**Comment by ghutchis** [comment]
The z-matrix editor is not provided in the binary installers. You can compile it yourself, e.g.
http://avogadro.cc/wiki/Compiling_on_Linux_and_Mac_OS_X

**Comment by dlopezduran** [comment]
OK, I'll take a look on it.
Thank you very much for the help, David.

**Comment by dlopezduran** [comment]
OK, I'll take a look on it. 
Thank you very much for the help, David. 


------------------------------- 

Dr. David López Durán. 
Theory Group at CIC Nanogune. 
San Sebastián, Spain.

**Comment by dlopezduran** [comment]
Hi all,
 I am trying to add the Z-matrix editor to my current version of Avogadro following the steps in the webpage suggested by ghutchis. However, I have again problems after doing "cmake ../avogadro-squared".  Taking into account the error message it is related with the Qt modules. I have been fighting with them, but I am unable to fix the problem. Right now, I have installed in my computer both Qt4 and Qt5 versions. As the computer messages warn that both versions may have conflicts, I have tried to remove Qt5 from my computer, with the Maintenance Tool; but I am not sure whether I achieved it or not. 
 These are the answers to the commands:

------------------------------------------------

command: cmake ../avogadro-squared

DOSX0099:avogadro-build dlopez$ pwd
/Users/dlopez/TRABAJO/avogadro-build
DOSX0099:avogadro-build dlopez$ cmake ../avogadro-squared
-- Downloading file at build time: libxml2-2.7.8.tar.gz
-- Downloading file at build time: zlib-1.2.8.tar.gz
-- Downloading file at build time: qt-everywhere-opensource-src-4.7.2.tar.gz
CMake Error at /usr/local/Cellar/cmake/3.5.2/share/cmake/Modules/FindQt4.cmake:1326 (message):
  Found unsuitable Qt version "" from NOTFOUND, this code requires Qt 4.x
Call Stack (most recent call first):
  CMakeLists.txt:20 (find_package)


-- Configuring incomplete, errors occurred!
See also "/Users/dlopez/TRABAJO/avogadro-build/CMakeFiles/CMakeOutput.log".
DOSX0099:avogadro-build dlopez$ 

--------------------------------------------------

command: brew info qt4

DOSX0099:TRABAJO dlopez$ pwd
/Users/dlopez/TRABAJO
DOSX0099:TRABAJO dlopez$ brew info qt4
qt: stable 4.8.7 (bottled), HEAD
Cross-platform application and UI framework
https://www.qt.io/
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/qt.rb
==> Dependencies
Required: openssl ✔
Optional: dbus ✘, mysql ✘, postgresql ✘
==> Options
--universal
	Build a universal binary
--with-dbus
	Build with dbus support
--with-docs
	Build documentation
--with-mysql
	Build with mysql support
--with-postgresql
	Build with postgresql support
--with-qt3support
	Build with deprecated Qt3Support module support
--without-webkit
	Build without QtWebKit module
--HEAD
	Install HEAD version
==> Caveats
We agreed to the Qt opensource license for you.
If this is unacceptable you should uninstall.

Qt Designer no longer picks up changes to the QT_PLUGIN_PATH environment
variable as it was tweaked to search for plug-ins provided by formulae in
  /usr/local/lib/qt4/plugins
DOSX0099:TRABAJO dlopez$ 

---------------------------------------------------

With respect to this answer, say that in my /usr/local/lib there is no any directory qt4. I have
been looking for the qt4 and qt5 set up directories; but I have not found them.

---------------------------------------------------

command: brew info qt5

DOSX0099:TRABAJO dlopez$ brew info qt5
qt5: stable 5.6.0 (bottled), HEAD [keg-only]
Version 5 of the Qt framework
https://www.qt.io/
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/qt5.rb
==> Dependencies
Build: xz ✔
Optional: dbus ✘
==> Options
--with-dbus
	Build with dbus support
--with-docs
	Build documentation
--with-examples
	Build examples
--with-mysql
	Build with mysql support
--with-oci
	Build with Oracle OCI plugin
--without-webengine
	Build without QtWebEngine module
--HEAD
	Install HEAD version
==> Caveats
We agreed to the Qt opensource license for you.
If this is unacceptable you should uninstall.

This formula is keg-only, which means it was not symlinked into /usr/local.

Qt 5 conflicts Qt 4 (which is currently much more widely used).
DOSX0099:TRABAJO dlopez$ 

---------------------------------------------------

A bit of help is greatly appreciated. Thanks a lot, David.

**Comment by ghutchis** [comment]
This is probably better handled on the avogadro-devel or avogadro-discuss mailing lists.

**Comment by dlopezduran** [comment]
OK thanks for the suggestion. 
Best regards, David. 


------------------------------- 

Dr. David López Durán. 
Theory Group at CIC Nanogune. 
San Sebastián, Spain.
