### ISSUE TITLE
Avogadro crashs when I try to open a log file generated in Gamess

### ISSUE THREAD

**Issue by minea80** [cryos/avogadro#854]
I opened the same file with other programs (Gabedit and wxMacMoIPlt) but when I try with Avogadro program closes 

![image](https://cloud.githubusercontent.com/assets/25487554/22518454/db80a88e-e869-11e6-8f0c-fdaf56929114.png)

**Comment by ghutchis** [comment]
This is a crash due to Open Babel. The bug has been fixed and the next Avogadro release should address it.

In the future, it would really help to upload an example file that causes the problem.
