### ISSUE TITLE
MSVC 2010 no longer compiles successfully

### ISSUE THREAD

**Issue by psavery** [cryos/avogadro#855]
Looks like a variable for pi, M_PI, is no longer being found in MSVC 2010.

A more important problem, however, is that MSVC 2010 crashes now when compiling wireengine.cpp (https://github.com/cryos/avogadro/blob/master/libavogadro/src/engines/wireengine.cpp). I'm guessing this is because of the new Eigen3 adaptations? I've tried it with Eigen 3.3.1 and Eigen 3.3.2, and it crashed on both. If the problem is in Eigen, it may be hard for us to fix. Here is the error from MSVC:

[ 16%] Building CXX object libavogadro/src/engines/CMakeFiles/wireengine.dir/wireengine.cpp.obj
wireengine.cpp
c1xx : fatal error C1001: An internal error has occurred in the compiler.
(compiler file 'msc1.cpp', line 1420)
 To work around this problem, try simplifying or changing the program near the locations listed above.
Please choose the Technical Support command on the Visual C++
 Help menu, or open the Technical Support help file for more information
        This error occurred in injected text:
        o8
Internal Compiler Error in E:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\cl.exe.  You will be prompted to send an error report to Microsoft later.
INTERNAL COMPILER ERROR in 'E:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\cl.exe'
    Please choose the Technical Support command on the Visual C++
    Help menu, or open the Technical Support help file for more information
NMAKE : fatal error U1077: '"E:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\cl.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"E:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"E:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\nmake.exe"' : return code '0x2'
Stop.

**Comment by ghutchis** [comment]
You should be able to use older Eigen3 (e.g., 3.2.x) - I'd try that first:
http://bitbucket.org/eigen/eigen/get/3.2.10.zip

**Comment by psavery** [comment]
Okay! Yeah that actually worked.

Is that true for all other operating systems also? As in, Eigen 3.2 compiles but not Eigen 3.3?

**Comment by ghutchis** [comment]
I can compile Eigen 3.3 on my Mac, and as far as I can tell, others tested with Fedora, etc.

**Comment by ghutchis** [comment]
I haven't had anyone try VS 2015. I'm going to close this for now.
