### ISSUE TITLE
Labels don't always show

### ISSUE THREAD

**Issue by davethecipo** [cryos/avogadro#856]
I don't understand fully how to reproduce this bug, but sometimes the labels don't show (obviously the "label" box is checked).

It seems to fail for big molecules...but not always.

I can try debugging on my own if someone has some hints on how to do it.

**Comment by ghutchis** [comment]
This is not a bug. The labels won't show if the atoms are too far from the camera and thus the label would be "too small."

**Comment by davethecipo** [comment]
Should labels appear if I zoom in close to the atoms? For example I zoom until 4 atoms are visible. Labels still don't show.

**Comment by mmeshhal** [comment]
I have the same problem. Did you find a solution? @davethecipo
