### ISSUE TITLE
Crash when opening in-progress multistep Gaussian log

### ISSUE THREAD

**Issue by Diazonium** [cryos/avogadro#864]
Ok, so I have ran into a crash when I tried to open the log file of a Gaussian run, that is still in progress.
The job is a multistep job, first there is a regular _Opt Freq_ job, than after that an NMR calculation. I have attached a short version of the gaussian input file.
The Opt Freq part has completed, so I wanted to open the log, to look at the finished structure, but Avogadro crashes when I try to open it. 
I am reluctant to publicly upload the exact log file that causes a crash due to the asinine policies of the Gaussian devs, but if someone needs it to reproduce, I can send the log privately.
[catalyst_opt_freq_SS_NMR_SMD_CHCl3.txt](https://github.com/cryos/avogadro/files/933947/catalyst_opt_freq_SS_NMR_SMD_CHCl3.txt)

PS. : I am using Avogadro 1.1.1, but looking at the release notes for 1.2, I see no crash fixes, so this should also happen in 1.2.

**Comment by ghutchis** [comment]
Can you try 1.2? There are a *lot* of fixes that aren't itemized.

I'd really need the exact log file to debug.

**Comment by Diazonium** [comment]
I guess you are right. I cannot reproduce this using 1.2.
