### ISSUE TITLE
Calling performAction from python terminal

### ISSUE THREAD

**Issue by acaly** [cryos/avogadro#867]
Hi,

I am new to Avogadro and python. I want to perform the "Auto Optimize" action from the python terminal but have not succeeded in this. The code I am using is similar to

```python
import Avogadro
ext = Avogadro.PluginManager.instance.extension("ForceField")
act = ext.actions[0]
ext.performAction(act, Avogadro.GLWidget.current())
```

The program crashes when the performAction is executing. Could you please help me to point out where is the mistake?

Thanks in advance.

**Comment by ghutchis** [comment]
My guess is that you have a null pointer somewhere in there, e.g., the extension isn't returned properly.

At this point, the Python interface in Avogadro v1 is unmaintained. It was a great idea, but there are too many points that can break. We're working on a better Python interface and terminal for Avogadro v2.

**Comment by acaly** [comment]
Thank you!
