### ISSUE TITLE
Per-atom vectors (not from vibration calculations)?

### ISSUE THREAD

**Issue by srk** [cryos/avogadro#882]
The ability to draw 3-D arrows on an existing displayed structure already exists in the code in the form of reading and animating vibrational modes from, e.g. a G09 .fchk/.log file or similar.

Would it be possible (either in the standard UI or using the API via Python) to add per-atom vectors (with a controllable scaling/colouring) to a displayed structure (ball or ball-and-stick) ? For example, a common extension to the '.xyz' file format is the (sometimes called 'xyz+vec' ) format, e.g:

2
Comment line
H 1.0 0.0 0.0 1.0 0.0 0.0
H -1.0 0.0 0.0 -1.0 0.0 0.0

Where the last 3 numbers in each atom record are the Cartesian components of a vector attached to the atom in question.

The ability to read and display such 'xyz+vec' files seamlessly would be very useful, but even a few hints about how to achieve this using Python + the API would be very useful. The simplest colouring scheme would be to have the arrows coloured according to the type of the atom the arrow is attached to.

**Comment by srk** [comment]
If the connection with OpenBabel is currently being reconsidered, can I vote for the inclusion of this feature again?

**Comment by ghutchis** [comment]
Huh? Avogadro v1 (this repo) is built directly on Open Babel code. If you want this kind of file, it needs to be implemented as an OB file format.

Any "reconsideration" is simply a question of whether Avogadro v1 (which is being discontinued) should be updated to the new OB-2.5/3.0 API before we stop development of Avo1 in favor of all effort occurring on Avo2 (openchemistry/avogadrolibs)

**Comment by srk** [comment]
OK, so the *only* changes required would be in the OB code, and strategically this should be done with the OB-2.5/3.0  code, yes?

**Comment by srk** [comment]
OK I added a feature request for support of this file format in OB.
