### ISSUE TITLE
Missing info on installation on MS Windows

### ISSUE THREAD

**Issue by miroi** [cryos/avogadro#885]
Hello,
in addition to #826 , I am thinking on https://www.appveyor.com/ CI builds at MS Windows.

Would you please provide some details on howto install avogadro on MS Windows from its source ? What packages are you using for that ?

Thanks.

**Comment by ghutchis** [comment]
See the development documentation: https://avogadro.cc/devel/compiling-windows/

**Comment by miroi** [comment]
Thanks, closing this ticket.
