### ISSUE TITLE
new superheavy element names for Avogadro

### ISSUE THREAD

**Issue by miroi** [cryos/avogadro#887]
Hi all, 

as I see, avogadro does not offer new element names of superheavy elements, like Nh, Fl, Og ... there is only small black ball marked as Xx.

example: AuNh 

![aunh](https://user-images.githubusercontent.com/1047336/33216712-4fca7c24-d135-11e7-848d-41ad773d1204.png)

**Comment by ghutchis** [comment]
This simply depends on what version of Open Babel you're using with Avogadro. 

Avogadro 1.2.x on Mac was built against Open Babel 2.4.1, which includes elements up to 118. I believe that's true for Avogadro 1.2.x binaries on Windows as well.
<img width="524" alt="screen shot 2017-11-24 at 8 53 41 pm" src="https://user-images.githubusercontent.com/41128/33226344-b097928e-d159-11e7-9a66-8e2bb00673f8.png">

I'm not sure what version of Avogaro that you're using, or what OS, but this isn't a bug in current versions.
