### ISSUE TITLE
Qt5 port

### ISSUE THREAD

**Issue by mbanck** [cryos/avogadro#891]
Will Avogadro-1 get ported to Qt5 at some point?

Debian (and I guess Ubuntu as well) will be dropping Qt4 for their next version, so Avogadro-1 would no longer be available then.

**Comment by cryos** [comment]
There are no current plans that I am aware of.

**Comment by ghutchis** [comment]
My feeling is that all effort should go into making Avogadro2 a suitable replacement for Avogadro 1.

See my comments about porting this code to OB-latest (which will likely be Open Babel v3).

**Comment by mbanck** [comment]
So is Avogadro2 now released and a suitable replacement for Avogadro1? The latter is about to be removed from Debian/Ubuntu due to the Qt4 removal.

**Comment by ghutchis** [comment]
@mbanck - I'm aiming for a strong Avogadro2 release this fall.

**Comment by cryos** [comment]
Let's do it! I was going to put out a new release soon to garner more feedback, and show off some of the recent additions. I know we likely can't keep everyone happy, but I would like to try and ensure we have most of the stuff people loved.
