### ISSUE TITLE
MAC OS avogadro V1.2.0 can not open gaussian input file gjf, even the gjf file is producted by itself.

### ISSUE THREAD

**Issue by zhouych87** [cryos/avogadro#959]
My avogadro can not open gaussian input file gjf. Even the gjf file is producted by itself.

give error:

Reading molecular file failed, file /Users/xxxxx/flip/test.gjf.
version infomation:

![image](https://user-images.githubusercontent.com/16185464/123111708-b3ec5380-d46f-11eb-82d9-af6cac305a2b.png)

It is in a MAC OS

**Comment by ghutchis** [comment]
Avogadro uses Open Babel to read files - OB has never supported reading Gaussian input because frankly people do too many weird things.

But if you want to help write a gjf / Gaussian input reader to Open Babel, it would certainly be accepted: https://github.com/openbabel/openbabel
