### ISSUE TITLE
Issue with auto-opt tool

### ISSUE THREAD

**Issue by phys1csb1tch** [cryos/avogadro#960]
For some reason when auto optimizing molecules that form a triangle in the geometry the field tempts to tie the two TM together. This has happened before for Cu2Rh2 molecules (and my advisor had to run the optimization in his version of Avogadro, that worked correctly) and now is happening with this Cu3Ru3. Sb knows how to fix it?
Image 1 optimizes to image 2
![IMG_20210816_180356_1](https://user-images.githubusercontent.com/89045651/129630772-8d312e6f-506a-4609-9b2b-7af821034f6a.jpg)
![IMG_20210816_181733](https://user-images.githubusercontent.com/89045651/129630873-c9de8d21-5c93-4ab2-b9e0-1c5cc73e2f3b.jpg)

**Comment by ghutchis** [comment]
I don't think I can recommend the Avogadro optimizer for a task like this. I'd highly suggest the free, open source XTB program, which runs approximate quantum calculations on XYZ format files (like your edit)
https://xtb-docs.readthedocs.io/en/latest/contents.html

 If you have questions, I'd recommend using the new forum https://discuss.avogadro.cc/
