### ISSUE TITLE
At least three files have Python syntax errors

### ISSUE THREAD

**Issue by cclauss** [cryos/avogadro#961]
$ `python3 -m pip install flake8`  # https://pypi.org/project/flake8
$ `flake8 . --count --select=E9,F63,F7 --show-source --statistics`
```
./avogadro/scripts/find-po-email.py:14:11: E999 SyntaxError: invalid syntax
    print email
          ^
./avogadro/libavogadro/examples/python/proteinextension.py:50:13: E999 SyntaxError: invalid syntax
      print atomId
            ^
./avogadro/libavogadro/src/python/unittest/template.py:9:3: E999 IndentationError: expected an indented block
  def test_test1(self):
  ^
3     E999 SyntaxError: invalid syntax
3
```

**Comment by ghutchis** [comment]
This app was released in 2007-2008 and last updated in 2016. It is **not** Py3 compatible (nor Qt5, Open Babel 3, etc.). It is no longer maintained as indicated in the header of this GitHub repo.

If you would like to help, Avogadro 2 is available at https://github.com/openchemistry/ and there are a variety of Python features, e.g.:
- https://github.com/openchemistry/avogenerators
- https://github.com/OpenChemistry/avogadro-cclib
- https://github.com/OpenChemistry/avogadro-commands

Feel free to stop by and say hello at https://discuss.avogadro.cc/

**Comment by cclauss** [comment]
`brew home avogadro` --> https://avogadro.cc

https://avogadro.cc
* Free, Open Source: Easy to install and all source code and documentation is [available to modify or extend](https://github.com/cryos/avogadro/).
    * Leads to https://github.com/cryos/avogadro instead of https://github.com/openchemistry
---
Also, perhaps this repo should be archived to make its status clear.
* https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/archiving-a-github-repository

**Comment by ghutchis** [comment]
I don't own the repo, so  I can't archive it, but I've  told @cryos 

Clearly a PR is needed to `homebrew-cask`. At the moment, the better webpage is `https://two.avogadro.cc/` - we haven't updated the main site because some users need features not available in `avogadrolibs`

Thanks for the PR - particularly in  `avogenerators`. Do you have any suggestions for the GitHub actions there?
